import { processHandler } from "handlers/canvas";

const json = {
  frameRate: 60,
  backgroundColor: "#fff",
  dimensions: {
    width: 720,
    height: 1280,
  },
  nodes: [
    {
      id: 20,
      start: 0,
      end: 5,
      type: "video",
      config: {
        src: "test/sources/source0.mp4",
        playbackRate: 1,
        trimStart: 0,
        trimEnd: 5,
        muted: false,
      },
      initialAttrs: {
        x: 0,
        y: 0,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        alpha: 1,
        tint: 16777215,
        pivotX: 0,
        pivotY: 0,
        skewX: 0,
        skewY: 0,
      },
      keyframes: [],
    },
  ],
};

// const json = {
//   frameRate: 30,
//   backgroundColor: "#000000",
//   dimensions: {
//     width: 1080,
//     height: 1920,
//   },
//   nodes: [
//     {
//       id: 22,
//       start: 5.133333,
//       end: 10.266666,
//       type: "video",
//       config: {
//         src: "https://storage.googleapis.com/aivideos-proxy-videos/task_cm9xs4vk300jsmp0129j4ub05/video_cm9yf9wqi0975mp01qsaigojx.mp4",
//         playbackRate: 1,
//         trimStart: 0,
//         trimEnd: 5.133333,
//         muted: false,
//       },
//       zIndex: 0,
//       initialAttrs: {
//         x: 608,
//         y: 816,
//         scaleX: 1,
//         scaleY: 0.9807692307692307,
//         rotation: 0,
//         alpha: 1,
//         tint: 16777215,
//         pivotX: 608,
//         pivotY: 832,
//         skewX: 0,
//         skewY: 0,
//       },
//       keyframes: [],
//       filters: [],
//     },
//     {
//       id: 6381131705,
//       start: 0,
//       end: 24.894688,
//       type: "audio",
//       config: {
//         src: "https://storage.googleapis.com/aivideos-assets/audio/Fun City.mp3",
//         playbackRate: 1,
//         trimStart: 0,
//         trimEnd: 24.894688,
//       },
//       initialAttrs: {},
//       keyframes: [],
//     },
//     {
//       id: 23,
//       start: 10.266666,
//       end: 15.366666,
//       type: "video",
//       config: {
//         src: "https://storage.googleapis.com/aivideos-original-videos/video_cm9yf9b6g0973mp0169kz1xi7.mp4",
//         playbackRate: 1,
//         trimStart: 0,
//         trimEnd: 5.1,
//         muted: false,
//       },
//       zIndex: 0,
//       initialAttrs: {
//         x: 608,
//         y: 816,
//         scaleX: 1,
//         scaleY: 1,
//         rotation: 0,
//         alpha: 1,
//         tint: 16777215,
//         pivotX: 608,
//         pivotY: 816,
//         skewX: 0,
//         skewY: 0,
//       },
//       keyframes: [],
//       filters: [],
//     },
//     {
//       id: 24,
//       start: 15.366666,
//       end: 20.499999000000003,
//       type: "video",
//       config: {
//         src: "https://storage.googleapis.com/aivideos-proxy-videos/task_cm9xs4vk300jsmp0129j4ub05/video_cm9yf7ede096zmp01jx5pmiuv.mp4",
//         playbackRate: 1,
//         trimStart: 0,
//         trimEnd: 5.133333,
//         muted: false,
//       },
//       zIndex: 0,
//       initialAttrs: {
//         x: 608,
//         y: 816,
//         scaleX: 1,
//         scaleY: 1,
//         rotation: 0,
//         alpha: 1,
//         tint: 16777215,
//         pivotX: 608,
//         pivotY: 816,
//         skewX: 0,
//         skewY: 0,
//       },
//       keyframes: [],
//       filters: [],
//     },
//     {
//       id: 21,
//       start: 0,
//       end: 5.133333,
//       type: "video",
//       config: {
//         src: "https://storage.googleapis.com/aivideos-proxy-videos/task_cm9xs4vk300jsmp0129j4ub05/video_cm9yf8ius0971mp01vz0zsbvj.mp4",
//         playbackRate: 1,
//         trimStart: 0,
//         trimEnd: 5.133333,
//         muted: false,
//       },
//       zIndex: 0,
//       initialAttrs: {
//         x: 608,
//         y: 816,
//         scaleX: 1,
//         scaleY: 1,
//         rotation: 0,
//         alpha: 1,
//         tint: 16777215,
//         pivotX: 608,
//         pivotY: 816,
//         skewX: 0,
//         skewY: 0,
//       },
//       keyframes: [
//         {
//           alpha: 0,
//           time: 0,
//           ease: "none",
//           index: 0,
//           id: 9541355300,
//         },
//         {
//           alpha: 1,
//           time: 1,
//           ease: "none",
//           index: 1,
//           id: 9731732639,
//         },
//       ],
//       filters: [],
//     },
//   ],
// };

async function main() {
  let resp = await processHandler({ json, startTime: 0, endTime: 4, fps: 10, output: "frames/chunk_0" });
  console.log(resp);
  // resp = await processHandler({
  //   json,
  //   startTime: 4,
  //   endTime: 8,
  //   fps: 10,
  //   output: "frames/chunk_1",
  // });
  // console.log(resp);
}

main();
