name: Build and Push Python Image to AWS ECR
on:
  push:
    branches: [aws-migration-test-1]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: ffmpeg-worker-server
  IMAGE_NAME: ffmpeg-worker
  ECR_REGISTRY: 079464146245.dkr.ecr.us-east-2.amazonaws.com
  EC2_INSTANCE_IP: 18.227.190.122
jobs:
  build-push-ecr:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major

      - name: Push Docker Image to ECR
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_TAG

      - name: SSH into EC2 and Deploy Docker Image
        uses: appleboy/ssh-action@v0.1.6
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          host: ${{ env.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,ECR_REGISTRY,ECR_REPOSITORY
          script: |
            # Configure AWS credentials
            mkdir -p ~/.aws
            echo "[default]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            region=$AWS_REGION" > ~/.aws/credentials

            # Mount EFS on the host
            sudo mkdir -p /mnt/efs
            sudo mount -t nfs4 -o nfsvers=4.1 172.31.11.60:/ /mnt/efs

            # Login to Amazon ECR
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

            # Pull the Docker image from ECR
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest

            # Stop the existing container if running
            docker rm -f my-ffmpeg-worker || true

            # Run the new container with the mounted EFS
            docker run -d \
              -p 80:3000 \
              -e FS_PATH=/mnt/efs \
              -e CLIENT_ID=QUINNCLIENTID \
              -e CLIENT_SECRET=QUINNCLIENTSECRET \
              -v /mnt/efs:/mnt/efs \
              --name my-ffmpeg-worker \
              $ECR_REGISTRY/$ECR_REPOSITORY:latest

            # Debug commands
            echo "Container logs:"
            sleep 2
            docker logs my-ffmpeg-worker

            echo "Container status:"
            docker ps -a

            echo "Network check:"
            netstat -tulpn | grep LISTEN
