name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [main]
env:
  IMAGE_NAME: ffmpeg-worker
  PROJECT_ID: shopify-442807
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker Client
        run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest us-west1-docker.pkg.dev/$PROJECT_ID/xelp/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us-west1-docker.pkg.dev/$PROJECT_ID/xelp/$IMAGE_NAME:$GIT_TAG
          docker push us-west1-docker.pkg.dev/$PROJECT_ID/xelp/$IMAGE_NAME:latest
          docker push us-west1-docker.pkg.dev/$PROJECT_ID/xelp/$IMAGE_NAME:$GIT_TAG
